alias: Freeze – Maintain ON while latched
description: "Keep heat tape on only in off-peak daylight, melt zone, and recent snow"
mode: restart
trigger:
  - platform: state
    entity_id: input_boolean.freeze_latch
    to: "on"
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: switch.heat_tape
    to: "off"
  - platform: numeric_state
    entity_id: sensor.openweathermap_temperature
    above: 39
    for: "01:00:00"
  - platform: numeric_state
    entity_id: sensor.openweathermap_temperature
    below: 25
    for: "01:00:00"
condition:
  - condition: time
    after: "06:00:00"
    before: "15:55:00"
  - condition: state
    entity_id: input_boolean.freeze_latch
    state: "on"
  - condition: state
    entity_id: input_boolean.snow_in_last_12_days
    state: "on"
action:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.openweathermap_temperature
            above: 25
          - condition: numeric_state
            entity_id: sensor.openweathermap_temperature
            below: 39
        sequence:
          - service: switch.turn_on
            target:
              entity_id: switch.heat_tape
      - conditions:
          - condition: or
            conditions:
              - condition: numeric_state
                entity_id: sensor.openweathermap_temperature
                above: 39
              - condition: numeric_state
                entity_id: sensor.openweathermap_temperature
                below: 25
        sequence:
          - service: switch.turn_off
            target:
              entity_id: switch.heat_tape
          - service: input_boolean.turn_off
            target:
              entity_id: input_boolean.freeze_latch
